version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  benchmark:
    build: .
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./benchmark.sh:/benchmark.sh
    environment:
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["./benchmark.sh"]